# Generated by Django 6.0.4 on 2026-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfc/'),
        ),
    ]
